"""Initial migration

Revision ID: 935d3a3e12d6
Revises: 
Create Date: 2025-12-24 21:19:34.154799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '935d3a3e12d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('account_type', sa.Enum('ASSET', 'LIABILITY', 'INCOME', 'EXPENSE', 'EQUITY', name='account_type'), nullable=False),
    sa.Column('parent_guid', sa.String(length=36), nullable=True),
    sa.Column('placeholder', sa.Boolean(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_guid'], ['accounts.guid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_table('transactions',
    sa.Column('post_date', sa.Date(), nullable=False),
    sa.Column('enter_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_table('vendors',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=50), nullable=True),
    sa.Column('address_phone', sa.String(length=255), nullable=True),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_table('purchase_orders',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('vendor_guid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'APPROVED', name='order_status'), nullable=False),
    sa.Column('date_opened', sa.DateTime(), nullable=True),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_guid'], ['vendors.guid'], ),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_table('splits',
    sa.Column('tx_guid', sa.String(length=36), nullable=False),
    sa.Column('account_guid', sa.String(length=36), nullable=False),
    sa.Column('memo', sa.String(length=255), nullable=True),
    sa.Column('value_num', sa.BigInteger(), nullable=False),
    sa.Column('value_denom', sa.BigInteger(), nullable=False),
    sa.Column('reconcile_state', sa.CHAR(length=1), nullable=True),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_guid'], ['accounts.guid'], ),
    sa.ForeignKeyConstraint(['tx_guid'], ['transactions.guid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_table('order_entries',
    sa.Column('order_guid', sa.String(length=36), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('i_acct_guid', sa.String(length=36), nullable=False),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['i_acct_guid'], ['accounts.guid'], ),
    sa.ForeignKeyConstraint(['order_guid'], ['purchase_orders.guid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_entries')
    op.drop_table('splits')
    op.drop_table('purchase_orders')
    op.drop_table('vendors')
    op.drop_table('transactions')
    op.drop_table('accounts')
    # ### end Alembic commands ###
